### ISSUE TITLE
Repo heavily out of date and won't run using latest version of typeorm and expo

### ISSUE THREAD

**Issue by cmcnicholas** [typeorm/expo-example#2]
Using latest TypeORM release and react native with Expo doesn't work, there are inconsistencies with how it tries to load the driver (it should be using the SQLite module of Expo), have tried running in web and native mobile Expo clients.

**Comment by cuibonobo** [comment]
I've made a [pull-request](https://github.com/typeorm/typeorm/pull/5536) on the TypeORM Expo driver to fix an issue to the Expo API, but I've updated the repo to build against TypeORM 0.2.21 and Expo SDK 36.0.
